# Generated by Django 5.2.10 on 2026-03-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Например: женщины, мужчины, аксессуары', max_length=100, unique=True, verbose_name='Slug (для URL, можно кириллица)'),
        ),
    ]
