# Generated by Django 5.2.10 on 2026-03-25 05:33

from django.db import migrations, models


def sync_listing_for_existing(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    for p in Product.objects.all():
        ids = [p.category_id]
        # slug-и по умолчанию как в settings
        slug = 'zhenshchinam' if p.gender == 'female' else 'muzhchinam'
        root = Category.objects.filter(slug=slug).first()
        if root:
            ids.append(root.id)
        p.listing_categories.set(ids)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allow_cyrillic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', help_text='Для выдачи в категориях «Мужчинам» / «Женщинам» (slug в GENDER_CATEGORY_SLUGS)', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_categories',
            field=models.ManyToManyField(blank=True, help_text='Заполняется автоматически: выбранная категория + корень по полу', related_name='listed_products', to='products.category', verbose_name='Категории для каталога'),
        ),
        migrations.RunPython(sync_listing_for_existing, migrations.RunPython.noop),
    ]
