# Generated by Django 5.2.10 on 2026-05-06

from django.db import migrations, models


def backfill_publication_status(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(status='active').update(publication_status='published')
    Product.objects.filter(status='moderation').update(publication_status='pending_review')
    Product.objects.filter(status='inactive').update(publication_status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий модерации'),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.CharField(
                choices=[
                    ('draft', 'Черновик'),
                    ('pending_review', 'На модерации'),
                    ('published', 'Опубликован'),
                    ('rejected', 'Отклонен'),
                ],
                default='draft',
                max_length=20,
                verbose_name='Статус публикации',
            ),
        ),
        migrations.RunPython(backfill_publication_status, migrations.RunPython.noop),
    ]
