# Generated by Django 5.2.10 on 2026-05-06

from django.db import migrations, models


def sync_existing_sellers(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='seller').update(seller_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_rejection_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отклонения продавца'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_status',
            field=models.CharField(
                choices=[
                    ('not_requested', 'Не запрошено'),
                    ('pending', 'На рассмотрении'),
                    ('approved', 'Подтвержден'),
                    ('rejected', 'Отклонен'),
                ],
                default='not_requested',
                max_length=20,
                verbose_name='Статус продавца',
            ),
        ),
        migrations.RunPython(sync_existing_sellers, migrations.RunPython.noop),
    ]
