# Generated by Django 5.2.10 on 2026-05-14 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('self_employed', 'Самозанятый'), ('ie', 'ИП'), ('llc', 'Юридическое лицо')], max_length=20, verbose_name='Тип продавца')),
                ('display_name', models.CharField(max_length=120, verbose_name='Название магазина (публичное)')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО контактного лица')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('description', models.TextField(verbose_name='Описание деятельности')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Согласие с правилами площадки')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время принятия правил')),
                ('status', models.CharField(choices=[('submitted', 'Подана'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='submitted', max_length=20, verbose_name='Статус заявки')),
                ('moderation_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий модератора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка продавца',
                'verbose_name_plural': 'Заявки продавцов',
                'ordering': ['-created_at'],
            },
        ),
    ]
